# Generated by Django 5.2 on 2025-04-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rsssource_remove_article_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='full_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.DateTimeField(null=True),
        ),
    ]
