# Generated by Django 5.2 on 2025-04-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_full_text_article_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='full_text',
            field=models.TextField(default='No text available'),
        ),
    ]
