# Generated by Django 5.2 on 2025-04-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_full_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysummary',
            name='important_articles',
        ),
    ]
