# Generated by Django 5.2 on 2025-05-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePolitics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('published', models.DateTimeField(null=True)),
                ('full_text', models.TextField(default='No text available')),
                ('image_url', models.URLField(null=True)),
            ],
            options={
                'verbose_name': 'ArticlePolitics',
            },
        ),
        migrations.CreateModel(
            name='DailySummaryPolitics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('summary', models.TextField(default='No summary available')),
            ],
        ),
        migrations.CreateModel(
            name='RSSSourcePolitics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article'},
        ),
    ]
